version: "3.9"

services:
  nginx:
    build: ./server/nginx
    ports:
      - 8000:80
      - 8001:443

  server:
    container_name: server
    build: ./server/spark
    stdin_open: true
    ports:
      - 3000:80
      - 3001:443
    volumes:
      - ./server/spark/src:/code/src

  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 3002:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
